---
# tasks file for alpine_310

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: upgrade all packages, if Alpine 3.10
  become: yes
  apk:
    upgrade: yes
  retries: "{{ default_retries }}" 
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure development related packages are installed, if Alpine 3.10
  become: yes
  apk: 
    name: ['util-linux', 'perl', 'sudo', 'tar', 'unzip', 'gzip', 'wget', 'lynx', 'nano', 'vim', 'emacs', 'bash-completion', 'git', 'python-pip']
  retries: "{{ default_retries }}" 
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common
