---
# tasks file for centos_7

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>


- name: enable cache in /etc/yum.conf
  become: yes
  lineinfile:
    path: /etc/yum.conf
    regexp: '^keepcache ='
    line: keepcache = 1
    state: present

- name: upgrade all packages, if CentOS 7
  become: yes
  yum:
    name: "*"
    exclude: docker-ce
    state: latest
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: install epel-release, if CentOS 7
  become: yes
  yum:
    name: epel-release
    state: latest
    state: latest
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure development related packages are installed, if CentOS 7
  become: yes
  yum:
    name: ['sudo', 'unzip', 'wget', 'lynx', 'nano', 'vim', 'emacs', 'bind-utils', 'bash-completion', 'bash-completion-extras']
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure an up-to-date git is installed, if CentOS 7
  become: yes
  block:
  - name: remove present version
    yum:
      name: git
      state: absent

  - name: ensure iuscommunity.org repo is installed.
    yum:
      name: https://centos7.iuscommunity.org/ius-release.rpm
      disable_gpg_check: yes
      state: present
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded

  - name: ensure git2u is installed
    yum:
      name: git2u
      state: latest
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded
  tags:
    - common
