---
# tasks file for common

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: fail if OS is not Ubuntu-bionic, Alpine 3.10 or CentOS 7
  fail:
    msg: "{{ ansible_distribution }} - {{ ansible_distribution_release }} is not Ubuntu-bionic or Alpine"
  when: ( ansible_distribution != 'Alpine' and not '3.10' in ansible_distribution_version) and ( ansible_distribution != 'Ubuntu' and ansible_distribution_release != 'bionic' ) and (ansible_distribution != 'CentOS' and ansible_distribution_major_version != '7')
  tags: common

- name: include centos_7.yml, when CentOS 7
  include: centos_7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  tags: common

- name: include ubunutu_bionic.yml, when Ubuntu-bionic
  include: ubuntu_bionic.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  tags: common

- name: include alpine_310.yml, when Alpine 3.10
  include: alpine_310.yml
  when: ansible_distribution == 'Alpine' and '3.10' in ansible_distribution_version
  tags: common

# https://docs.sonarqube.org/latest/requirements/requirements/
- name: configure vm memory, file_max, file descriptors and threads
  block:
  - name: ensure vm.max_map_count=262144 is configured in /etc/sysctl.conf 
    become: yes
    lineinfile:
      dest: /etc/sysctl.conf
      state: present
      regexp: "^vm.max_map_count="
      line: "vm.max_map_count=262144"

  - name: ensure fs.file-max=65536 is configured in /etc/sysctl.conf
    become: yes
    lineinfile:
      dest: /etc/sysctl.conf
      state: present
      regexp: "^fs.file-max="
      line: "fs.file-max=65536"

  - name: Ensure /etc/security exists 
    become: yes
    file:
      path: /etc/security
      state: directory

  - name: Ensure /etc/security/limits.conf exists
    become: yes
    file:
      path: /etc/security/limits.conf
      state: touch

  - name: ensure root can open at least 65536 file descriptors by configuring in /etc/security/limits.conf
    become: yes
    lineinfile:
      dest: /etc/security/limits.conf
      state: present
      regexp: "^root   -   nofile   65536"
      line: "root   -   nofile   65536"

  - name: ensure root can open root can open at least 4096 threads by configuring in /etc/security/limits.conf
    become: yes
    lineinfile:
      dest: /etc/security/limits.conf
      state: present
      regexp: "^root   -   nproc    4096"
      line: "root   -   nproc    4096"
  tags:
    - common

- name: "ensure /etc/profile PATH includes $HOME/.local/bin"
  become: yes
  block:
    - lineinfile:
        dest: /etc/profile
        regexp: "^export PATH=$HOME/.local/bin:$PATH"
        state: absent

    - lineinfile:
        dest: /etc/profile
        line: "export PATH=$HOME/.local/bin:$PATH"
        insertafter: EOF
  tags:
    - comon

- name: ensure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes
  tags:
    - common

- name: configure 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  tags:
    - common

- name: ensure {{ ansible_user_id }} is added to wheel group
  become: yes
  user: 
    name: "{{ ansible_user_id }}"
    groups: wheel 
    append: yes 
    state: present 
  tags:
    - common
