cp ansible/roles/k3s-server/tasks/retrieve_container_image.yml ansible/roles/k3s-agent/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/docker-registry/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/gitlab/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/golang-container-image/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/owasp-zap2docker-stable-image/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/plantuml-server/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/python-container-image/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/sonarqube/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/standalone-chrome-container-image/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/standalone-firefox-container-image/tasks/.
cp ansible/roles/k3s-server/tasks/*image.yml ansible/roles/taiga/tasks/.
