#!/usr/bin/env bash

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

docker build -t nemonik/plantuml-server:{{ plantuml_server_version }}{% if http_proxy %} --build-arg http_proxy={{ http_proxy }} --build-arg HTTP_PROXY={{ http_proxy }}{% endif %}{% if https_proxy %} --build-arg https_proxy={{ https_proxy }} --build-arg HTTPS_PROXY={{ https_proxy }}{% endif %}{% if no_proxy %} --build-arg no_proxy={{ no_proxy }} --build-arg NO_PROXY={{ no_proxy }} {% endif %} .
docker image inspect nemonik/plantuml-server:{{ plantuml_server_version }}
docker tag nemonik/plantuml-server {{ registry_host }}:{{ registry_port }}/nemonik/plantuml-server
docker push {{ registry_host }}:{{ registry_port }}/nemonik/plantuml-server
