#!/bin/bash
### BEGIN INIT INFO
# Provides:          django
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Stop/start django
### END INIT INFO

APPNAME=taiga-back
USER=`whoami`
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APPMODULE=taiga.wsgi
DAEMON=gunicorn
BIND=0.0.0.0:8000
PIDFILE=/tmp/django.pid
LOGFILE=/dev/stdout
WORKERS=3

. /lib/lsb/init-functions

if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi

case "$1" in
  start)
        log_daemon_msg "Starting deferred execution scheduler" "$APPNAME"
        cd /taiga/taiga-back
        $DAEMON --daemon --bind=$BIND --pid=$PIDFILE --workers=$WORKERS --user=$USER --log-file=$LOGFILE $APPMODULE
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution scheduler" "$APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
