FROM ruby:alpine as alpine

{% if CA_CERTIFICATES %}
# Update CA Certs
RUN apk add -U --no-cache ca-certificates wget

RUN cd /usr/local/share/ca-certificates/ && {% for ca in CA_CERTIFICATES %} wget {{ ca }} &&{% endfor %} update-ca-certificates
{% endif %}

FROM ruby:alpine
MAINTAINER Michael Joseph Walsh <nemonik@gmail.com>

{% if CA_CERTIFICATES%}
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
{% endif %}

RUN apk add --update build-base libxml2-dev libffi-dev git openssh-client
RUN gem install --no-document --source https://rubygems.org --version {{ inspec_version }} inspec
RUN gem install --no-document --source https://rubygems.org --version {{ inspec_version }} inspec-bin
RUN apk del build-base