---
# tasks file for /vagrant/ansible/roles/standalon-firefox-container-image

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- set_fact:
    images:
      - { repository: "selenium/standalone-firefox", tag: "{{ selenium_standalone_firefox_version }}" }

- name: create /home/{{ ansible_user_id }}/standalone-firefox-container-image
  file:
    path: "/home/{{ ansible_user_id }}/standalone-firefox-container-image"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - standalone-firefox-container-image

- name: template files into /home/{{ ansible_user_id }}/standalone-firefox-container-image
  template:
    src: templates/{{ item }}.j2
    dest: /home/{{ ansible_user_id }}/standalone-firefox-container-image/{{ item }}
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"   
  with_items:
    - "Dockerfile" 
    - "dockerfile_build.sh"
    - "push_into_private_repo.sh"
  tags:
    - standalone-firefox-container-image

- name: make /home/{{ ansible_user_id }}/standalone-firefox-container-image/dockerfile_build.sh executable
  file: 
    path: /home/{{ ansible_user_id }}/standalone-firefox-container-image/{{ item }}
    mode: "u=rwx,g=r,o=r"
  with_items:
    - "push_into_private_repo.sh"
    - "dockerfile_build.sh"
  tags:
    - standalone-firefox-container-image

- name: emplace images into private container registry
  block:
  - name: load {{ images }} from cache
    include_tasks: retrieve_container_image.yml
    loop: "{{ images }}"

  - name: pull {{ images }} container images
    docker_image:
      name: "{{ item.repository }}:{{ item.tag }}"
      source: pull
      timeout: "{{ docker_timeout }}"
    retries: "{{ docker_retries }}"
    delay: "{{ docker_delay }}"
    register: result
    until: result is succeeded
    loop: "{{ images }}"

  - name: tag and push {{ images }} into private registry
    shell: |
      docker tag {{ item.repository }}:{{ item.tag }} {{ registry_host }}:{{ registry_port }}/{{ item.repository }}:{{ item.tag }}
      docker push {{ registry_host }}:{{ registry_port }}/{{ item.repository }}:{{ item.tag }}
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded
    loop: "{{ images }}"
    
  - name: build nemonik/standalone-firefox:{{ selenium_standalone_firefox_version }} image and push into private registry
    docker_image:
      name: nemonik/standalone-firefox
      tag: "{{ selenium_standalone_firefox_version }}"
      repository: "{{ registry_host }}:{{ registry_port }}/nemonik/standalone-firefox"
      build:
        path: /home/{{ ansible_user_id }}/standalone-firefox-container-image
        pull: yes
        args:
          http_proxy: "{{ http_proxy|default('') }}"
          HTTP_PROXY: "{{ http_proxy|default('') }}"
          https_proxy: "{{ https_proxy|default('') }}"
          HTTPS_PROXY: "{{ https_proxy|default('') }}"
          NO_PROXY: "{{ no_proxy|default('') }}"
          no_proxy: "{{ no_proxy|default('') }}" 
      push: yes
    retries: "{{ docker_retries }}"
    delay: "{{ docker_delay }}"
    register: result
    until: result is succeeded
  tags:
    - standalone-firefox-container-image

- name: save {{ images }} to cache
  include_tasks: cache_container_image.yml
  loop: "{{ images }}"
  tags:
    - standalone-firefox-container-image
