FROM registry:{{ registry_version }}
MAINTAINER Michael Joseph Walsh <mjwalsh@mitre.org>

{% if CA_CERTIFICATES %}
RUN apk add --update openssl ca-certificates wget
 
RUN cd /usr/local/share/ca-certificates/ && {% for ca in CA_CERTIFICATES %} wget {{ ca }} &&{% endfor %} update-ca-certificates
{% endif %}

COPY config.yml /etc/docker/registry/config.yml
 
CMD ["serve", "/etc/docker/registry/config.yml"]
