#!/usr/bin/env bash

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

docker build -t nemonik/standalone-chrome:{{ selenium_standalone_chrome_version }} .
docker image inspect nemonik/standalone-chrome:{{ selenium_standalone_chrome_version }}
